# Generated by Django 5.0.13 on 2025-12-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hoteleria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
