# Generated by Django 5.0.13 on 2025-12-10 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hoteleria', '0002_servicio_delete_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='app_hoteleria.reserva')),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
