# Generated by Django 5.0.13 on 2025-12-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hoteleria', '0003_pago_delete_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
